version: '3'
services:
  grizly_scheduler:
    image: grizly_scheduler:latest
    build: .
    ports:
      - "8786:8786"
      - "8787:8787"
    container_name: grizly_scheduler
    restart: "always"