version: '3'
services:
  base_notebook:
    image: base_notebook:latest
    build:
      context: ../../
      dockerfile: docker/base_notebook/Dockerfile
      args:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
      - ALTERNATIVE_PROXY=${PROXY}
    ports:
      - "8888:8888"
    container_name: base_notebook
