version: '3'
services:
  base_notebook:
    image: grizly_base:latest
    build: 
      context: ../../
      dockerfile: docker/base_notebook/Dockerfile
      args:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - ALTERNATIVE_PROXY=${ALTERNATIVE_PROXY}
    ports:
      - "8888:8888"
    container_name: base_notebook
