version: '3'
services:
  grizly_notebook:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - HTTP_PROXY=${PROXY}
        - HTTPS_PROXY=${PROXY}
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
      - GRIZLY_PROXY=${PROXY}
      - GRIZLY_DASK_SCHEDULER_ADDRESS=${GRIZLY_DASK_SCHEDULER_ADDRESS}
      - GRIZLY_EXTRACT_STAGING_SCHEMA=${GRIZLY_EXTRACT_STAGING_SCHEMA}
      - GRIZLY_EXTRACT_PROD_SCHEMA=${GRIZLY_EXTRACT_PROD_SCHEMA}
      - GRIZLY_REDIS_HOST=${GRIZLY_REDIS_HOST}
    ports:
      - "8889:8888"
    volumes:
      - ../..:/home/analyst
      - ../../.config/odbc.ini:/etc/odbc.ini
    container_name: grizly_notebook
    restart: "always"
  sqlmanager:
    image: sqlpad/sqlpad:latest
    volumes:
      - ../../sqlpad:/var/lib/sqlpad
    environment:
      - SQLPAD_SESSION_MINUTES=999999
    ports:
      - "3000:3000"
    container_name: sqlpad
    restart: "always"
  dask_scheduler:
    image: acoeteam/dask_scheduler:latest
    ports:
      - "8787:8787"
    container_name: dask_scheduler
    restart: "always"
  dask_worker:
    image: acoeteam/dask_worker:latest
    volumes:
      - .../..:/home/analyst
      - ../../.config/odbc.ini:/etc/odbc.ini
    environment:
      - HTTPS_PROXY=${PROXY}
    depends_on:
      - dask_scheduler
    links:
      - grizly_notebook
    restart: "always"
