version: '3'
services:
  grizly_notebook:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - GRIZLY_PROXY=${GRIZLY_PROXY}
      - GRIZLY_DASK_SCHEDULER_ADDRESS=${GRIZLY_DASK_SCHEDULER_ADDRESS}
      - GRIZLY_EXTRACT_STAGING_EXTERNAL_SCHEMA=${GRIZLY_EXTRACT_STAGING_EXTERNAL_SCHEMA}
      - GRIZLY_EXTRACT_STAGING_SCHEMA=${GRIZLY_EXTRACT_STAGING_SCHEMA}
      - GRIZLY_REDIS_HOST=${GRIZLY_REDIS_HOST}
    ports:
      - "8889:8888"
    volumes:
      - ./docker_home:/home/analyst
      - ./docker_home/.config/odbc.ini:/etc/odbc.ini
    container_name: grizly_notebook
    restart: "always"
  sqlmanager:
    image: sqlpad/sqlpad:latest
    volumes:
      - ./docker_home/sqlpad:/var/lib/sqlpad
    environment:
      - SQLPAD_SESSION_MINUTES=999999
    ports:
      - "3000:3000"
    container_name: sqlpad
    restart: "always"
